[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/ai/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/webhooks/*"
  to = "/.netlify/functions/:splat"
  status = 200