-- ============================================================================
-- Migration: 20260707_add_missing_schema
-- Adds: ai_videos, brand_kit tables; missing columns on videos and profiles;
--       updated usage table columns; RLS policies; realtime publications.
-- ============================================================================

-- ============================================================================
-- ai_videos table
-- Stores AI-personalized video generations (voice clone + Muapi lipsync/omni)
-- ============================================================================

create table if not exists public.ai_videos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  og_video_id text,
  og_video_url text,
  url text,
  preview text,
  status text default 'pending',
  notes text,
  contact jsonb default '{}'::jsonb,
  training_audio text,
  language text
);

create index if not exists idx_ai_videos_user on public.ai_videos (user_id);
create index if not exists idx_ai_videos_status on public.ai_videos (status);

-- ============================================================================
-- brand_kit table
-- Per-user brand color preferences (1-1 with auth.users)
-- ============================================================================

create table if not exists public.brand_kit (
  user_id uuid primary key references auth.users(id) on delete cascade,
  primary_color text,
  secondary_color text,
  primary_text_color text,
  secondary_text_color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================================
-- Missing columns on public.videos
-- ============================================================================

alter table public.videos add column if not exists final_url text;
alter table public.videos add column if not exists training_audio text;
alter table public.videos add column if not exists ai_preview text;
alter table public.videos add column if not exists language text;
alter table public.videos add column if not exists media_status text default 'pending';

-- ============================================================================
-- Missing columns on public.profiles
-- ============================================================================

alter table public.profiles add column if not exists onboard_completed boolean default false;
alter table public.profiles add column if not exists job_title text;

-- ============================================================================
-- Updated usage table columns
-- Adds: service, tokens_in, tokens_out, video_id
-- Renames existing details -> meta, cost_estimate -> cost
-- ============================================================================

alter table public.usage add column if not exists service text;
alter table public.usage add column if not exists tokens_in int default 0;
alter table public.usage add column if not exists tokens_out int default 0;
alter table public.usage add column if not exists video_id uuid references public.videos(id) on delete set null;

-- Rename cost_estimate -> cost if it still exists
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'usage' and column_name = 'cost_estimate') then
    alter table public.usage rename column cost_estimate to cost;
  end if;
end $$;

-- Rename details -> meta if it still exists
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'usage' and column_name = 'details') then
    alter table public.usage rename column details to meta;
  end if;
end $$;

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.ai_videos enable row level security;
alter table public.brand_kit enable row level security;

-- ai_videos: users manage their own rows
drop policy if exists "ai_videos_own" on public.ai_videos;
create policy "ai_videos_own" on public.ai_videos
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- brand_kit: users manage their own row
drop policy if exists "brand_kit_own" on public.brand_kit;
create policy "brand_kit_own" on public.brand_kit
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- usage: users read/write their own rows
drop policy if exists "usage_own" on public.usage;
create policy "usage_own" on public.usage
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ============================================================================
-- Realtime publications
-- ============================================================================

alter publication supabase_realtime add table public.ai_videos;
alter publication supabase_realtime add table public.brand_kit;
