CREATE TABLE IF NOT EXISTS "public"."usage" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" uuid,
    "model" text,
    "provider" text,
    "action" text,
    "details" jsonb,
    "cost_estimate" numeric,
    "tokens_used" bigint
);

ALTER TABLE "public"."usage" OWNER TO "postgres";

ALTER TABLE "public"."usage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COMMENT ON TABLE "public"."usage" IS 'API usage tracking for Muapi and OpenAI';