CREATE TABLE IF NOT EXISTS public.usage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid,
    model text,
    provider text,
    action text,
    details jsonb,
    cost_estimate numeric
);

-- Grant basic privileges (adjust for your environment)
GRANT SELECT, INSERT ON public.usage TO anon;
GRANT SELECT, INSERT ON public.usage TO authenticated;
