-- ============================================================================
-- Migration: 20260718_videco_app_tables (ISOLATED, SHARED-DB SAFE)
-- ============================================================================
-- This project's DB is shared with several other apps, so this migration is
-- deliberately scoped to ONLY the tables the Videco app needs, and it:
--   * Uses CREATE TABLE IF NOT EXISTS everywhere (idempotent, no clobber).
--   * Does NOT touch the existing shared `profiles` / `auth.users` objects
--     (those are owned by other apps).
--   * Uses auth.uid()-based RLS (not tenant_id) to avoid depending on columns
--     that belong to other apps.
--   * Adds columns to `videos`/`usage` only with IF NOT EXISTS guards.
-- Run with: supabase db push --linked   (or supabase migration up)
-- ============================================================================

-- Tenants (workspaces). IF NOT EXISTS so it never clobbers another app's table.
create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Videos (Muapi outputs)
create table if not exists public.videos (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  url text,
  type text,
  source text default 'muapi',
  model text,
  job_id uuid,
  prompt text,
  duration_seconds int,
  metadata jsonb default '{}'::jsonb,
  final_url text,
  training_audio text,
  ai_preview text,
  language text,
  media_status text default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Images
create table if not exists public.images (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  url text not null,
  source text default 'muapi',
  model text,
  job_id uuid,
  prompt text,
  kind text default 'generated',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Audios
create table if not exists public.audios (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  url text not null,
  kind text not null,
  model text,
  job_id uuid,
  prompt text,
  duration_seconds int,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Jobs (Muapi generation tracking)
create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  type text not null,
  provider text default 'muapi',
  model text,
  request_id text,
  status text not null default 'processing',
  input jsonb,
  output jsonb,
  error text,
  resource_type text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

-- Scripts (OpenAI generations)
create table if not exists public.scripts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  prompt text not null,
  output text,
  model text default 'gpt-4o-mini',
  kind text default 'script',
  created_at timestamptz not null default now()
);

-- AI personalized videos (voice clone + Muapi lipsync/omni)
create table if not exists public.ai_videos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  og_video_id text,
  og_video_url text,
  url text,
  preview text,
  status text default 'pending',
  notes text,
  contact jsonb default '{}'::jsonb,
  training_audio text,
  language text
);

-- Brand kit (1-1 with auth.users)
create table if not exists public.brand_kit (
  user_id uuid primary key references auth.users(id) on delete cascade,
  primary_color text,
  secondary_color text,
  primary_text_color text,
  secondary_text_color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Sub-accounts (team invites) — referenced by useFetchTeamData
create table if not exists public.sub_accounts (
  id uuid primary key default gen_random_uuid(),
  main_account uuid,
  shared_account text,
  name text,
  role text default 'member',
  shared_account_user uuid,
  workspace_id uuid,
  status text default 'pending',
  created_at timestamptz not null default now()
);

-- Leads / Submissions / Feedback
create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  video_id uuid references public.videos(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  email text,
  phone text,
  message text,
  data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  video_id uuid references public.videos(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  video_id uuid references public.videos(id) on delete cascade,
  question text,
  answer text,
  session_id text,
  created_at timestamptz not null default now()
);

-- Plan (per-user plan) — referenced by useUserPlan
create table if not exists public.plan (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  plan_name text default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Usage tracking (Muapi + OpenAI)
create table if not exists public.usage (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  model text,
  provider text,
  action text,
  meta jsonb,
  cost numeric,
  tokens_in int default 0,
  tokens_out int default 0,
  video_id uuid references public.videos(id) on delete set null
);

-- ============================================================================
-- Indexes (IF NOT EXISTS)
-- ============================================================================
create index if not exists idx_videos_user on public.videos (user_id);
create index if not exists idx_videos_tenant on public.videos (tenant_id);
create index if not exists idx_videos_type on public.videos (type);
create index if not exists idx_images_user on public.images (user_id);
create index if not exists idx_audios_user on public.audios (user_id);
create index if not exists idx_jobs_user on public.jobs (user_id);
create index if not exists idx_jobs_request_id on public.jobs (request_id);
create index if not exists idx_scripts_user on public.scripts (user_id);
create index if not exists idx_leads_tenant on public.leads (tenant_id);
create index if not exists idx_submissions_tenant on public.submissions (tenant_id);
create index if not exists idx_feedback_tenant on public.feedback (tenant_id);
create index if not exists idx_ai_videos_user on public.ai_videos (user_id);
create index if not exists idx_ai_videos_status on public.ai_videos (status);
create index if not exists idx_sub_accounts_shared on public.sub_accounts (shared_account);

-- ============================================================================
-- Row Level Security — auth.uid() based (does NOT touch shared profiles)
-- ============================================================================
alter table public.tenants enable row level security;
alter table public.videos enable row level security;
alter table public.images enable row level security;
alter table public.audios enable row level security;
alter table public.jobs enable row level security;
alter table public.scripts enable row level security;
alter table public.ai_videos enable row level security;
alter table public.brand_kit enable row level security;
alter table public.sub_accounts enable row level security;
alter table public.leads enable row level security;
alter table public.submissions enable row level security;
alter table public.feedback enable row level security;
alter table public.plan enable row level security;
alter table public.usage enable row level security;

-- Helper policies: users manage rows where user_id = auth.uid()
drop policy if exists "videco_videos_own" on public.videos;
create policy "videco_videos_own" on public.videos
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_images_own" on public.images;
create policy "videco_images_own" on public.images
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_audios_own" on public.audios;
create policy "videco_audios_own" on public.audios
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_jobs_own" on public.jobs;
create policy "videco_jobs_own" on public.jobs
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_scripts_own" on public.scripts;
create policy "videco_scripts_own" on public.scripts
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_ai_videos_own" on public.ai_videos;
create policy "videco_ai_videos_own" on public.ai_videos
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_brand_kit_own" on public.brand_kit;
create policy "videco_brand_kit_own" on public.brand_kit
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_plan_own" on public.plan;
create policy "videco_plan_own" on public.plan
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_usage_own" on public.usage;
create policy "videco_usage_own" on public.usage
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_leads_own" on public.leads;
create policy "videco_leads_own" on public.leads
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "videco_submissions_auth" on public.submissions;
create policy "videco_submissions_auth" on public.submissions
  for all to authenticated using (true) with check (true);

drop policy if exists "videco_feedback_auth" on public.feedback;
create policy "videco_feedback_auth" on public.feedback
  for all to authenticated using (true) with check (true);

drop policy if exists "videco_sub_accounts_own" on public.sub_accounts;
create policy "videco_sub_accounts_own" on public.sub_accounts
  for all to authenticated using (shared_account_user = auth.uid()) with check (shared_account_user = auth.uid());

drop policy if exists "videco_tenants_own" on public.tenants;
create policy "videco_tenants_own" on public.tenants
  for all to authenticated using (id = (
    select tenant_id from public.videos where user_id = auth.uid() limit 1
  )) with check (true);

-- ============================================================================
-- Realtime (optional, safe to add)
-- ============================================================================
alter publication supabase_realtime add table public.videos;
alter publication supabase_realtime add table public.ai_videos;
alter publication supabase_realtime add table public.jobs;
